# Generated by Django 2.2.7 on 2020-04-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioinfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModelCorona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.CharField(max_length=100)),
                ('discovered', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
